import { ReactNode } from "react";
import Head from "next/head";
import { Layout as LayoutAnt, ConfigProvider, theme } from "antd";
import { useAtom } from "jotai";

import Navbar from "./navbar/Navbar";
import Footer from "./footer/Footer";
import { themeAtom } from "@/atom/theme";
import styled from "styled-components";

const { Content } = LayoutAnt;

const Wrapper = styled(LayoutAnt)`
  && {
    height: 100vh;
    justify-content: space-between;
  }
`;
export default function Layout({ children }: { children: ReactNode }) {
  const [mode] = useAtom(themeAtom);

  return (
    <>
      <Head>
        <title>Said Aoussar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ConfigProvider
        theme={{
          token: { colorPrimary: "#13C2C2", colorSuccess: "#13C2C2" },
          algorithm:
            mode === "light" ? theme.defaultAlgorithm : theme.darkAlgorithm
        }}
      >
        <Wrapper>
          <div>
            <Navbar />
            <Content>{children}</Content>
          </div>
          <Footer />
        </Wrapper>
      </ConfigProvider>
    </>
  );
}
