import Head from "next/head";
import { Inter } from "@next/font/google";
import { Layout, ConfigProvider, theme } from "antd";
import Navbar from "components/navbar/Navbar";
import { themeAtom } from "@/atom/theme";
import { useAtom } from "jotai";
import { Intro } from "components/intro/Intro";
import Skills from "components/skills/Skills";
import Projects from "components/projects/Projects";
import Contact from "components/contact/Contact";
import Footer from "components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

const { Header } = Layout;

export default function Home() {
  const [mode] = useAtom(themeAtom);
  return (
    <>
      <Head>
        <title>Said Aoussar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ConfigProvider
        theme={{
          token: { colorPrimary: "#13C2C2", colorSuccess: "#13C2C2" },
          algorithm:
            mode === "light" ? theme.defaultAlgorithm : theme.darkAlgorithm
        }}
      >
        <Layout>
          <Navbar />
          <Intro />
          <Skills />
          <Projects />
          <Contact />
          <Footer />
        </Layout>
      </ConfigProvider>
    </>
  );
}
